# permissions for end users to view languagemodels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: languagemodel-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: lm-controller
    app.kubernetes.io/part-of: lm-controller
    app.kubernetes.io/managed-by: kustomize
  name: languagemodel-viewer-role
rules:
- apiGroups:
  - ai.contrib.fluxcd.io
  resources:
  - languagemodels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ai.contrib.fluxcd.io
  resources:
  - languagemodels/status
  verbs:
  - get
